name: codecov
  uses: codecov/codecov-action@v3
  env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_SECRET }}
    comment: false
coverage:
  status:
    patch: false
    project:
      default:
        informational: true
